# Create a pod and set individual environment variables from configmap

apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-pod-1
spec:
  containers:
    - name: nginx-configmap-container
      image: nginx
      env:
        - name: AUTHOR
          valueFrom:
            configMapKeyRef:
              name: app-config-map
              key: author
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config-map
              key: color
        - name: COUNTRY
          valueFrom:
            configMapKeyRef:
              name: app-config-map
              key: country
  nodeSelector:
    kubernetes.io/os: linux
--- 

# Create a pod and set all environment variables from configmap

apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-pod-2
spec:
  containers:
    - name: nginx-configmap-container
      image: nginx
      envFrom:
        - configMapRef:
            name: app-config-map
  nodeSelector:
    kubernetes.io/os: linux
---

# Create a pod and load configmap as volume. This will create a file for each key in configmap. If key has dot in it, then it will create a directory and file inside it. If the file content changes, it will be reflected in the pod.

apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-pod-3
spec:
  containers:
    - name: nginx-configmap-container
      image: nginx
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: app-config-map
  nodeSelector:
    kubernetes.io/os: linux
