# Create a pod and set individual environment variables from configmap
apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-pod-1
spec:
  containers:
    - name: nginx-configmap-container
      image: nginx
      env:
        - name: AUTHOR
          valueFrom:
            configMapKeyRef:
              name: app-settings-cm-1
              key: author
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: app-settings-cm-1
              key: color
        - name: COUNTRY
          valueFrom:
            configMapKeyRef:
              name: app-settings-cm-1
              key: country
      resources:
        requests:
          cpu: '250m'
          memory: '128Mi'
        limits:
          cpu: '1'
          memory: '512Mi'
  nodeSelector:
    kubernetes.io/os: linux
---
# Create a pod and set all environment variables from configmap
apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-pod-2
spec:
  containers:
    - name: nginx-configmap-container
      image: nginx
      envFrom:
        - configMapRef:
            name: app-settings-cm-2
      resources:
        requests:
          cpu: '250m'
          memory: '128Mi'
        limits:
          cpu: '1'
          memory: '512Mi'
  nodeSelector:
    kubernetes.io/os: linux
---
# Create a pod and load configmap as volume. This will create a file for each key in configmap. If key has dot in it, then it will create a directory and file inside it. If the file content changes, it will be reflected in the pod.
apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-pod-3
spec:
  containers:
    - name: nginx-configmap-container
      image: nginx
      resources:
        requests:
          cpu: '250m'
          memory: '128Mi'
        limits:
          cpu: '1'
          memory: '512Mi'
      volumeMounts:
        - name: cm-volume
          mountPath: /etc/config
  volumes:
    - name: cm-volume
      configMap:
        name: app-settings-cm-3
  nodeSelector:
    kubernetes.io/os: linux
