apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stateful-set
spec:
  selector:
    matchLabels:
      app: mysql-ss
  serviceName: mysql-h
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql-ss
    spec:
      containers:
      - name: mysql-ss-container
        image: mysql
