apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  serviceAccountName: dashboard-sa
  containers:
    - name: nginx-container
      image: nginx:alpine
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
