apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  serviceAccountName: my-service-account
  containers:
    - name: my-container
      image: my-image:latest