apiVersion: v1
kind: Pod
metadata:
  name: webapp-color-pod
spec:
  containers:
    - name: webapp-color-pod-container
      image: prasadhonrao/python-flask-webapp-color
      env:
        - name: APP_COLOR
          value: "pink"
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
  nodeSelector:
    kubernetes.io/os: linux
