apiVersion: v1
kind: Service
metadata:
  name: node-express-hello-world-app-service
spec:
  type: LoadBalancer
  selector:
    app: node-express-hello-world-app
  ports:
  - port: 9000
    targetPort: 8080
