apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pattern-pod
spec:
  containers:
  - name: producer # this is the main container
    image: ubuntu
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo $(hostname) $(date) >> /var/log/index.html; sleep 10; done"]
    volumeMounts:
    - name: web-content-volume
      mountPath: /var/log
  - name: consumer # this is the sidecar container
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
    ports:
      - containerPort: 80
    volumeMounts:
    - name: web-content-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: web-content-volume 
    emptyDir: {}
