apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    run: httpd
spec:
  containers:
  - image: httpd:2.4.38
    name: httpd-container
    ports:
    - containerPort: 80
    resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always