apiVersion: v1
kind: Service
metadata:
  name: mvc-app-nodeport-app-service
spec:
  selector:
    app: mvc-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort
