apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: db-credentials
  containers:
    - name: nginx-secret-container
      image: nginx
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets/db-credentials
          readOnly: true
