apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    version: v1
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
            requests:
              cpu: '0.5'
              memory: '256Mi'
      nodeSelector:
        kubernetes.io/os: linux
