apiVersion: v1
kind: Pod
metadata:
  name: secret-env-viewer-pod
spec:
  containers:
    - name: secret-env-viewer-container
      image: prasadhonrao/env-viewer
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
  nodeSelector:
    kubernetes.io/os: linux