apiVersion: v1
kind: Pod
metadata:
  name: secret-env-viewer-pod-1
spec:
  containers:
    - name: secret-env-viewer-container
      image: prasadhonrao/js-node-env-viewer
      # Load all the secrets as environment variables
      envFrom:
        - secretRef:
            name: db-secret
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
  nodeSelector:
    kubernetes.io/os: linux