apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: bXlkYnVzZXI= # base64-encoded 'mydbuser'
  password: bXlzZWNyZXRwb3NlcnRwYXNzd29yZA== # base64-encoded 'mysecretpassword'