apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv-pvc-pod
spec:
  containers:
    - name: nginx-pv-container
      image: nginx:alpine
      resources:
        limits:
          cpu: '100m'
          memory: '128Mi'
      command:
        - /bin/sh
        - -c
        - while true; do echo $(date) >> /mnt/logs/output; sleep 1; done
      volumeMounts:
        - name: logs-pvc
          mountPath: /mnt/logs
          readOnly: true
  volumes:
    - name: logs-pvc
      persistentVolumeClaim:
        claimName: nginx-pvc
