apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-env-viewer-deployment
spec:
  selector:
    matchLabels:
      app: node-env-viewer-pod
  template:
    metadata:
      labels:
        app: node-env-viewer-pod
    spec:
      containers:
      - name: node-env-viewer-container
        image: prasadhonrao/node-env-viewer:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MESSAGE
          value: "Hello from the environment variable!"
