apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      app: nginx-app 
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      nodeSelector: # only schedule it on linux nodes
        kubernetes.io/os: linux  
      containers:
        - name: nginx-container
          image: nginx
          resources:
            limits:
              memory: "128Mi" 
              cpu: "200m"
