apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
  - port: 8080
    targetPort: 8080 # Note that targetPort of node app is 8080, not default 80