apiVersion: v1
kind: Pod
metadata:
  name: node-express-hello-world-app
  labels:
    name: node-express-hello-world-app
spec:
  containers:
  - name: node-express-hello-world-app-container
    image: prasadhonrao/node-express-hello-world-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"