apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    release: v1
    app: nginx-app
spec:
  terminationGracePeriodSeconds: 10 # Default is 30
  restartPolicy: Always # Always, OnFailure, Never
  containers:
    - name: nginx-container
      image: nginx:alpine
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
  nodeSelector:
    kubernetes.io/os: linux
