apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ambassador-app
  template:
    metadata:
      labels:
        app: ambassador-app
    spec:
      containers:
        - name: server
          image: prasadhonrao/ambassador-server
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

        - name: ambassador
          image: prasadhonrao/ambassador
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - name: weather-server
          image: prasadhonrao/ambassador-weather-api
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: weather-api
spec:
  selector:
    app: weather-api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-app
spec:
  selector:
    app: ambassador-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
