apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: dev-namespace
  labels:
    release: v1
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources: 
        limits:
          cpu: "100m"
          memory: "128Mi"
      ports:
        - name: http-port
          containerPort: 80


