apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-liveness-probe
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      ports:
        - name: http-port
          containerPort: 80
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 15 # wait 15 seconds before performing the first probe
        timeoutSeconds: 2 # wait 2 seconds for the probe to respond
        periodSeconds: 5 # perform the probe every 5 seconds
        failureThreshold: 1 # consider the probe as failed after 1 failed attempt
        successThreshold: 1 # consider the probe as successful after 1 successful attempt 
  nodeSelector:
    kubernetes.io/os: linux