apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-readiness-probe
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      ports:
        - name: http-port
          containerPort: 80
      readinessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 2
        periodSeconds: 5
  nodeSelector:
    kubernetes.io/os: linux