apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    release: v1
spec:
  containers:
    - name: redis-container
      image: redis
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
      ports:
        - containerPort: 6379
      