apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper-container
      image: prasadhonrao/ubuntu-sleeper
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
      command: ["/bin/sleep"] # this will replace entrypoint instruction in the image
      args: ["20"] # this will replace cmd value in the image
