apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    app: flask-pod
spec:
  containers:
    - name: flask-pod-container
      image: prasadhonrao/flask-pod:latest
      ports:
        - containerPort: 5000
