apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - image: node-app:2.0
        name: node-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"