apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3  # Set the desired number of replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - name: http-port
              containerPort: 80
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: hardware
          operator: Equal
          value: high-performance
          effect: NoSchedule
