kind: Pod
apiVersion: v1
metadata:
  name: azure-managed-disk-pod
spec:
  containers:
    - name: newpod
      image: nginx:latest
      volumeMounts:
        - mountPath: '/mnt/azure'
          name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk-pvc
