apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 3
  minReadySeconds: 1
  progressDeadlineSeconds: 10
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: node-app
      env: green
  template:
    metadata:
      labels:
        app: node-app
        env: green
    spec:
      containers:
      - image: prasadhonrao/node-app:2.0
        name: node-app