apiVersion: v1
kind: Service
metadata:
  name: node-app-lb-service
spec:
  type: LoadBalancer
  selector:
    app: node-app
    env: green # change it to green once the test is done
  ports:
  - port: 8080
    targetPort: 8080