apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    version: v1
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
      nodeSelector:
        kubernetes.io/os: linux
