apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
    - name: 'http'
      port: 80
      targetPort: 80
    - name: 'nodeport'
      port: 31000
      targetPort: 80
