apiVersion: v1
kind: Service
metadata:
  name: nginx-node-port-service
spec:
  type: NodePort
  ports:
    - name: http-port
      port: 80 # this is the port on the service that other services will use to connect to this service
      targetPort: 80 # this is the container port
      nodePort: 31000 # this is the port exposed on the node. Valid range is 30000-32767.
  selector: # this connects the service to the pods
    app: nginx-app
