apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  template:
    metadata:
      name: math-add-job
    spec:
      restartPolicy: Never # OnFailure or Never or Always
      containers:
      - name: math-add-job-container
        image: ubuntu
        command:
         - "expr"
         - "3"
         - "+"
         - "2"

