apiVersion: v1
kind: Pod
metadata:
  name: javascript-todo-app
  labels:
    name: javascript-todo-app
spec:
  containers:
  - name: javascript-todo-app-container
    image: prasadhonrao/javascript-todo-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
        - name: http-port
          containerPort: 3000
      