apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    release: v1
    app: nginx-app
spec:
  containers:
    - name: nginx-container
      image: nginx:alpine
      securityContext:
        capabilities:
          add: ["SYS_TIME"]
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"