apiVersion: v1
kind: Pod
metadata:
  name: linux-python-pod
  labels:
    app: linux-python-app
spec:
  containers:
    - name: linux-python-container
      image: python
      command: ['cmd']
      args: ['/k', 'python', '-c', "print('Hello, Windows Pod')"]
      resources:
        limits:
          cpu: '100m'
          memory: '128Mi'
  nodeSelector:
    kubernetes.io/os: linux
