apiVersion: v1
kind: Pod
metadata:
  name: windows-python-pod
  labels:
    app: windows-python-app
spec:
  containers:
    - name: windows-python-container
      image: python
      command: ["cmd"]
      args: ["/k", "python", "-c", "print('Hello, Windows Pod')"]
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
  nodeSelector:
    kubernetes.io/os: windows
